### ISSUE TITLE
Adding Lookup By Airline for Flight Search

### ISSUE THREAD

**Issue by mkaburis** [mkaburis/Airside-Database-Management-System#1]
One standard requirement that should be reasonable to implement is that users should be able to perform a query in one of two ways in the flight search:

- By origin to destination (_currently implemented_)
- By airline name and flight number

It is not unreasonable for instance for me to search for `Delta 2009` and an origin from `TPA` with a destination to `ATL`. This query is not possible under the current implementation of Flight Search.

**Comment by master-faz** [comment]
It is almost possible, we just need to add the Airline part. We can do 2009 TPA ATL and it shows the result. I also have the code ready so it only shows flights +- 1 day from today, since realistically this is what matters. However we could add a calander to select a range of dates to show

**Comment by master-faz** [comment]
I currently have it showing all dates since we don't have an interface to add and remove flights

**Comment by master-faz** [comment]
Changed. Now you can do AA 24, AA, or 24 and it will query based on which one is passed.
